### ISSUE TITLE
Official Maven/Gradle Installation issue

### ISSUE THREAD

**Issue by caryyu** [AdoptOpenJDK/homebrew-openjdk#456]
The homebrew official Maven or Gradle installation will alway pick the openjdk as its dependency definition even if AdoptOpenJDK has been installed, any ideas or suggestions to solve this issue if i still want to keep the following installation command for maven:

```shell
brew install maven
``` 

> the above command just ignored AdoptOpenJDK

**Comment by aahlenst** [comment]
There's nothing we can do about it. Homebrew is hardcoded to use `openjdk`, see https://github.com/Homebrew/homebrew-core/blob/master/Formula/maven.rb#L12. And to my knowledge, Homebrew does not have the capabilities of dpkg or rpm to define a Provides-like directive so that we could declare that we provide `openjdk`. Workaround: Let it install `openjdk` and set `JAVA_HOME` according to your needs. Maven/Gradle will pick that up.
