### ISSUE TITLE
Cask for JDK 16-EA

### ISSUE THREAD

**Issue by garydgregory** [AdoptOpenJDK/homebrew-openjdk#513]
Any chance of getting a cask for JDK 16-EA?

**Comment by karianna** [comment]
Unlikely I'm afraid - we tend to only run full installers for the release builds.

**Comment by aahlenst** [comment]
You can obtain a PKG from https://adoptopenjdk.net/nightly.html?variant=openjdk16&jvmVariant=hotspot if that's what you're looking for. It's the same that would be installed via a hypothetical cask.

We don't do EA builds like OpenJDK does but daily builds. So that would result in a daily updated cask. I don't know if that's desirable.
