### ISSUE TITLE
Brew install jdk8 hang

### ISSUE THREAD

**Issue by chaokunyang** [AdoptOpenJDK/homebrew-openjdk#524]
When I install adoptopenjdk8 in macos 13, it build images and hangs:
![image](https://user-images.githubusercontent.com/12445254/111428453-7a020780-8732-11eb-96e9-23a4768bb328.png)
Why installing jdk needs to make images? I thought it just copy some binaries and files to some directories.

**Comment by aahlenst** [comment]
You're not installing a prebuilt AdoptOpenJDK binary, you're about to install the `openjdk` formula which builds from source because Homebrew insists that only builds from jdk.java.net are true OpenJDK builds and you can only get the current version (at the time of writing: 16) and preview versions (17) from there. Instructions for installing AdoptOpenJDK 8 are on https://github.com/adoptopenjdk/homebrew-openjdk.

**Comment by chaokunyang** [comment]
So if I understand right, If I need to install java8 on macos by command line, I must builds from source?

**Comment by aahlenst** [comment]
> I must builds from source?

No. We have prebuilt binaries for macOS. But you have to follow the instructions on https://github.com/adoptopenjdk/homebrew-openjdk to install them.

**Comment by chaokunyang** [comment]
Seems `brew tap homebrew/cask-versions` or `brew tap AdoptOpenJDK/openjdk` will install jdk from source.  `brew install --cask adoptopenjdk8` won't build from source.
